### ISSUE TITLE
The ideas

### ISSUE THREAD

**Issue by GetContented** [KentBeck/Prune#1]
Sure like the idea of this ;-) Bit sad there's no code to go with it. :)

Was watching a video of you the other day talking about your mentoring practices and you mentioned a non-text-based IDE. Assuming it's probably this :). Quite interested in this kind of thing, too (been thinking about this for about 15 years on and off, to various degrees).

Gotta say it: love your books. Bit of a massive fan :)

Any movement on this project in a space visible by me?

**Comment by pthrasher** [comment]
+1

**Comment by GetContented** [comment]
Since reading this, I've had a bit of a massive look at react, clojure, om, pedestal and lighttable, including the upcoming previews of what the lighttable are calling aurora - their next project. Mathematica also does a lot in this space, but it's obviously proprietary. It looks like a lot of good people are working on isolating and understanding mutability in the editor. (True mutation can only really be modeled by a series of time-recorded "create" events). Clojure does this pretty completely with respect to the innards of the computer (ie to programs), basically because it's a LISP (and a really good modern one - they've made LISP approachable to non-LISPers, IMHO... bit hard to tell because I've been into LISP for a long time)

I wouldn't be surprised given reactjs if Facebook hadn't already implemented such editors... it'd be nice if we could stop repeating ourselves at the program-creation level. I'm so sick of typing the word "function" in when writing javascript, for example. ;-) And also, I'm completely sick of making syntax errors. The computer knows all the possible syntax of my programming language. It knows all of the possible forms I can create, so why am I typing them in again and again as though it doesn't know what I'm talking about? I'm really not "creating" programs, I'm referring to chunks of code and sequencing my referencings, and yet I still have to type them in like I'm actually creating them. Guh. It makes me feel like programmers, for all that we're supposed to be a smart bunch, are just idiotically stupid when it comes to our own tools.

We need an editor where it's easy to make the kinds of forms and mutations we make on those forms (and yes, where it's actually impossible to create syntax errors)... so if I spend a lot of time wrapping things in a certain pattern, that pattern should be known by my editor, along with all the other possible syntactical forms that my "language" supports. Basically the editor needs to know all about the underlying AST and the transformations I make on it as I go. This reminds me of that project... what was it called? oh yeah, intentional programming ;-)

**Comment by rychipman** [comment]
This made it to the HN front page today...no code??
